# Generated by Django 6.0.3 on 2026-03-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectedReview",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("review", models.TextField()),
                ("doc_id", models.CharField(blank=True, max_length=255, null=True)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "stg_movie_reviews",
                "managed": False,
            },
        ),
    ]
